spring.application.name=multidatabase

spring.mongodb.database=atividadedb
spring.mongodb.uri=mongodb://localhost:27017/atividadedb

spring.datasource.url=jdbc:postgresql://localhost:5432/atividadedb
spring.datasource.username=usuario
spring.datasource.password=senha
spring.jpa.hibernate.ddl-auto=update

spring.main.allow-bean-definition-overriding=true
